### PR TITLE
scorer script and random baseline for FNC-1

### PR DESCRIPTION
**Pull request by bgalbraith**
A pure Python implementation of the scoring method for FNC-1. Includes built-in null baseline (all unrelated) and a test baseline csv containing uniformly random labels.

### CODE REVIEW

**Comment by bgalbraith** [comment]
I found and corrected a bug in the first commit. I also, uh, went a bit overboard and added more metrics, including a formatted confusion matrix. should be done adding things at this point

**Comment by braingineer** [comment]
Hi @bgalbraith , great stuff!  As a side point, I wrote this up yesterday but haven't had a chance to PR it.  It converts the json version of the data into pandas form.  It might be useful to you / this pr =). 

https://gist.github.com/braingineer/279ee681eeb027cb9d480d77b02b2f43

**Comment by bgalbraith** [comment]
Hey @braingineer. I saw that earlier, nice work! I opted for a pure Python (no numpy/pandas/etc) approach here so that anyone could run the scorer without any additional library requirements.

**Comment by braingineer** [comment]
Aah makes sense! 

(side note: waiting for @delip to do merges, hence why I haven't merged it :P)

It might be worth having a pure-python eval script and then a library (that uses the scipy-stack) as a starting point for teams.  I'll open up an issue for discussion.

**Comment by delip** [comment]
Great stuff @bgalbraith. Looks good to me & thanks for being an extra pair of 👀 @braingineer :)
Merging!

**Pull request merged**
